import unittest
from Chatbot import page3

class TestChatbot(unittest.TestCase):
    """
    A test class for the Chatbot functionality.
    
    This class contains unit tests for testing the methods of the Chatbot (page3) class.
    """
    
    def setUp(self):
        """
        Set up method called before each test method.

        Initializes a page3 instance for testing.
        """
        self.bot = page3()

    def test_response_generator(self):
        """
        Test the response_generator method of page3.

        This test verifies that the response generated by response_generator is one
        of the expected predefined responses.
        """
        response = list(self.bot.response_generator())  # Convert generator to list
        expected_responses = [
            "Hello there! How can I assist you today?",
            "Hi, human! Is there anything I can help you with?",
            "Do you need help?",
        ]
        # Check if any of the responses in response is in expected_responses
        self.assertTrue(any(resp in expected_responses for resp in response),
                        "The response should be one of the predefined responses")

    def test_handle_user_input(self):
        """
        Test the handle_user_input method of page3.

        This test verifies that handle_user_input returns True for non-empty input
        and False for empty input.
        """
        self.assertTrue(self.bot.handle_user_input("Hello"),
                        "The method should return True for non-empty input")
        self.assertFalse(self.bot.handle_user_input(""),
                         "The method should return False for empty input")

if __name__ == '__main__':
    unittest.main()
